LR_CROPPED_SIZE = 100
UPSCALE = 4
HR_CROPPED_SIZE = UPSCALE * LR_CROPPED_SIZE

TRAIN_HR_DIR = "DIV2K/DIV2K_train_HR"
TRAIN_LR_DIR = "DIV2K/DIV2K_train_LR_bicubic/X4"
VAL_HR_DIR = "DIV2K/DIV2K_valid_HR"
VAL_LR_DIR = "DIV2K/DIV2K_valid_LR_bicubic/X4"

REAL_VALUE = 0.9
FAKE_VALUE = 0.0

BATCH_SIZE = 8
EPOCHS = 30

N_RESBLK_G = 20
LR = 0.0001
BETAS = (0.5, 0.9)

VGG_LOSS_COEF = 0.006
ADVERSARIAL_LOSS_COEF = 0.001