LR_CROPPED_SIZE = 100
UPSCALE = 4
HR_CROPPED_SIZE = UPSCALE * LR_CROPPED_SIZE

TRAIN_HR_DIR = "DIV2K/DIV2K_train_HR"
TRAIN_LR_DIR = "DIV2K/DIV2K_train_LR_bicubic/X4"
VAL_HR_DIR = "DIV2K/DIV2K_valid_HR"
VAL_LR_DIR = "DIV2K/DIV2K_valid_LR_bicubic/X4"

REAL_VALUE = 1.0
FAKE_VALUE = 0.0
BATCH_SIZE = 8
EPOCHS = 30
LR = 0.01
N_RESBLK_G = 20

VGG_LOSS_COEF = 0.006
ADVERSARIAL_LOSS_COEF = 0.001