LR_CROPPED_SIZE = 100
HR_CROPPED_SIZE = 400

TRAIN_HR_DIR = "../DIV2K/DIV2K_train_HR"
TRAIN_LR_DIR = "../DIV2K/DIV2K_train_LR_bicubic/X4"
VAL_HR_DIR = "../DIV2K/DIV2K_valid_HR"
VAL_LR_DIR = "../DIV2K/DIV2K_valid_LR_bicubic/X4"

BATCH_SIZE = 8
EPOCHS = 30
LR = 0.001
N_RESBLK_G = 4
UPSCALE = 4